### ISSUE TITLE
Maturin build doesn't include the entry_points in setup.py?

### ISSUE THREAD

**Issue by WestXu** [PyO3/maturin#623]
* Your python version (`python -V`): `Python 3.8.10`
 * Your pip version (`pip -V`): `pip 21.2.4 from /home/coder/miniconda/lib/python3.8/site-packages/pip (python 3.8)`
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): `pyo3`
 * Does `cargo build` work? `Yes.`

So here is my project structure:
```
myproject/__init__.py
myproject/api.py
src/lib.rs
src/main.rs
setup.py
.gitignore
Cargo.toml
```

And my `setup.py`:
```python
import setuptools

setuptools.setup(
    name="myproject",
    version="0.0.1",
    author='WestXu',
    author_email='xu-lai-xi@qq.com',
    packages=setuptools.find_packages(),
    entry_points={
        'console_scripts': [
            'mycli = myproject.api:cli',
        ],
    },
)
```

When install using `maturin develop --release && pip install -e .`, everything works fine with my cli. While when install using `maturin build --release && pip install target/wheels/myproject-0.1.0-cp38-cp38-linux_x86_64.whl`, my cli does not work, and running `mycli` in terminal gives `sh: mycli: command not found`.

**Comment by WestXu** [comment]
And the reason why I use `setup.py` instead of `pyproject.toml` is that I really need the `pip install --editable`. Can anyone share some tricks to make maturin and editable installation both work?

BTW, happen to find this while searching for solutions: https://www.python.org/dev/peps/pep-0660/
Will maturin support this?

**Comment by messense** [comment]
maturin only works with PEP 517 so it doesn't read setup.py. 
Even if we implemented PEP 660, it still would require https://github.com/pypa/pip/pull/8212 to land first.

**Comment by WestXu** [comment]
Ok. Looks like https://github.com/pypa/pip/pull/8212 will be finished soon. 

And I've tried using `maturin develop` to replace `pip install -e .`, thought this could be a more legit way to achive this, but the entry_points is not working either. So it's by https://github.com/PyO3/maturin/issues/213 I guess. 

Either of them working will get my problem solved.

**Comment by WestXu** [comment]
Also I tried this popular shim, from https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for:
```python
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()

```

Then `pip install -e .` gives:
```
    ERROR: Command errored out with exit status 1:
     command: /home/lxuwsl/miniconda3/envs/newenv/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/d/git-project/jzgateway/setup.py'"'"'; __file__='"'"'/mnt/d/git-project/jzgateway/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/d/git-project/jzgateway/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
```

**Comment by messense** [comment]
Add `setuptools` to `build-system.requires` list of `pyproject.toml`.

**Comment by WestXu** [comment]
Thanks. I can `pip install -e .` now, but entry_points defined in `pyproject.toml` still won't work this way. `command not found`.

**Comment by messense** [comment]
maturin will never support reading metadata from `setup.py`, so I'm closing this issue. Opened #624 to track PEP 660 support.

**Comment by messense** [comment]
BTW, it would be great if you want to work #213

**Comment by WestXu** [comment]
Wish I could contribute, but after reading the source code for a while, I conclude that maybe it's beyond my capacity.

I guess python packaging stuff is just too complicated for me to make full sense of it.

**Comment by messense** [comment]
Basically we need to generate a script based on this template https://github.com/pypa/pip/blob/0de0b8dd9f21642dc6d0e00bfa8913f4964b1706/src/pip/_vendor/distlib/scripts.py#L41-L48 and put it in virtualenv's bin directory.

**Comment by messense** [comment]
I've partially implemented #213 in #633 (Windows support is lacking). Please give it a try, you can install the pre-release version by `pip install -U --pre maturin`.

**Comment by WestXu** [comment]
Works like a charm. Appreciate it. 

This is my daily python driver now.
